import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
export default function Home({users}) {
  const [usersState,setUserState] = useState(users)
  const random = (length) => {
    let chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
     // Pick characers randomly
     let str = '';
     for (let i = 0; i < length; i++) {
         str += chars.charAt(Math.floor(Math.random() * chars.length));
     }
    return str
  }

  const findAllUser = async () => {
    const res = await fetch('http://localhost:3000/api/test/getAllUser')
    const users = await res.json()
    setUserState(users.test)
  }

  const addNewUser = async () => {
    const name = random(6)
    const email = random(13)
    const postBody = {
      name: name,
      email: email
    }
    const res = await fetch('http://localhost:3000/api/test/add',{
      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      body: JSON.stringify(postBody)
    })
    const resjson = await res.json()
    console.log(resjson)

    findAllUser()
  } 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description} onClick={addNewUser}>
          ADD NEW USER
        </p>

        <div className={styles.grid}>
          {
            usersState.map((user,index )=> (
              <a href="https://nextjs.org/docs" className={styles.card} key={index}>
                <h2>{user.name}</h2>
                <p>{user.email}</p>
              </a>
            ))
          }
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  const res = await fetch('http://localhost:3000/api/test/getAllUser')
  const users = await res.json()
  
  return {
    props: {users: users.test}, 
  }
}
